server:
  port: 8081

spring:
  profiles: dev
  mvc:
    throw-exception-if-no-handler-found: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/docker-template?autoReconnect=true&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    platform: mysql
#  flyway:
#    user: root
#    password: root
#    url: jdbc:mysql://localhost:3306/docker-template?autoReconnect=true&useSSL=false